---
- hosts: mania:eco:osa
  become: true
  tasks:
    - debug: msg={{ item }} 
      with_items:
        - poseidon
        - zeus
        - jupiter
        - ceres
        - hera
        - dionysos
        - hermes
        - demeter
        - athena
        - maia
        - apollo
        - artemis
        - ares
      when: inventory_hostname == item
