---
- hosts: demeter
  become: yes
  gather_facts: no
  vars:
    weave_env:
        DOCKER_HOST: unix:///var/run/weave/weave.sock
  tasks:
    - file: path=/bin/weave state=absent
    - get_url: url=https://git.io/weave dest=/bin/weave mode=777
    - name: forward
      shell: iptables -D FORWARD -j REJECT --reject-with icmp-host-prohibited
      ignore_errors: yes
    - name: input
      shell: iptables -D INPUT -j REJECT --reject-with icmp-host-prohibited
      ignore_errors: yes
    - shell: iptables-save

    - firewalld: port=9876/tcp permanent=true state=enabled zone=public
    - firewalld: port=5432/tcp permanent=true state=enabled zone=public
    - firewalld: port=3306/tcp permanent=true state=enabled zone=public
    - firewalld: port=80/tcp permanent=true state=enabled zone=public
    - service: name=docker state=restarted
    - shell: weave launch
    - name: setup mysql
      environment: "{{weave_env}}"
      docker:
        name: mariadb
        image: mariadb:latest
        state: present
        pull: always
        volumes:
           - "/srv/mariadb:/var/lib/mysql"
        ports:
           - "3306:3306"
        restart_policy: always
        restart_policy_retry: 5
        cpu_set: 2-10
        memory_limit: 8096MB
        env:
           MYSQL_ROOT_PASSWORD: 
    - copy: src=/home/qtheya/ansible/roles/selectel/demeter/my.cnf dest=/srv/my.cnf 
    - shell: docker cp /srv/my.cnf mariadb:/etc/mysql/my.cnf
    - shell: docker commit mariadb
    - name: start mysql
      environment: "{{weave_env}}"
      docker:
        name: mariadb
        image: mariadb:latest
        state: started
    - name: setup postgresql
      environment: "{{weave_env}}"
      docker:
        name: postgresql
        image: postgres:latest
        state: started
        pull: always
        volumes:
           - "/srv/postgresql:/var/lib/postgresql"
        ports:
           - "5432:5432"
        restart_policy: always
        restart_policy_retry: 5
        cpu_set: 11-20
        memory_limit: 8096MB
    - name: setup nginx
      environment: "{{weave_env}}"
      docker:
        name: nginx
        image: nginx:latest
        state: started
        pull: always
        volumes:
           - "/storage/www:/var/www"
           - "/srv/nginx/conf.d:/etc/nginx/conf.d"
           - "/srv/nginx/nginx.conf:/etc/nginx/nginx.conf"
        ports:
           - "80:80"
           - "443:443"
        restart_policy: always
        restart_policy_retry: 5
        cpu_set: 8-12
        memory_limit: 4048MB
    - name: setup memcached
      environment: "{{weave_env}}"
      docker:
        name: memcached
        image: memcached:latest
        state: started
        pull: always
        restart_policy: always
        restart_policy_retry: 5
        cpu_set: 21-22
        memory_limit: 4048MB
    - name: setup php5
      environment: "{{weave_env}}"
      docker:
        name: php5fpm
        image: php5/latest 
        state: started
        pull: always
        volumes:
           - "/storage/www:/var/www"
        restart_policy: always
        restart_policy_retry: 5
        cpu_set: 23-28
        memory_limit: 8096MB
        docker_api_version: 1.18
    - name: setup php7
      environment: "{{weave_env}}"
      docker:
        name: php7fpm
        image: php7/latest
        state: started
        pull: always
        volumes:
           - "/storage/www:/var/www"
        restart_policy: always
        restart_policy_retry: 5
        cpu_set: 29-34
        memory_limit: 8096MB
        docker_api_version: 1.18
