---
- hosts: demeter
  become: yes
  gather_facts: no
  tasks:
    - hostname: name=demeter
    - sysctl: name=fs.file-max value=1000000 sysctl_set=yes
    - sysctl: name=vm.overcommit_memory value=2 sysctl_set=yes
    - sysctl: name=vm.dirty_ratio value=10 sysctl_set=yes
    - sysctl: name=vm.max_map_count value=131072 state=absent
    - sysctl: name=net.ipv4.tcp_synack_retries value=2 sysctl_set=yes
    - sysctl: name=net.ipv4.tcp_rfc1337 value=1 sysctl_set=yes
    - sysctl: name=net.ipv4.tcp_fin_timeout value=15 sysctl_set=yes
    - sysctl: name=net.ipv4.tcp_keepalive_time value=300 sysctl_set=yes
    - sysctl: name=net.ipv4.tcp_keepalive_probes value=5 sysctl_set=yes
    - sysctl: name=net.ipv4.tcp_keepalive_intvl value=15 sysctl_set=yes
    - sysctl: name=net.core.optmem_max value=25165824 sysctl_set=yes
    - sysctl: name=net.ipv4.ip_forward value=1 sysctl_set=yes
    - sysctl: name=net.ipv4.conf.all.forwarding value=1 sysctl_set=yes
    - sysctl: name=net.ipv4.conf.default.forwarding value=1 sysctl_set=yes
    - sysctl: name=net.ipv6.conf.all.forwarding value=1 sysctl_set=yes
    - sysctl: name=net.ipv6.conf.default.forwarding value=1 sysctl_set=yes reload=yes
    - sysctl: name=kernel.sysrq value=0 sysctl_set=yes
    - sysctl: name=fs.suid_dumpable value=0 sysctl_set=yes
    - sysctl: name=kernel.kptr_restrict value=1 sysctl_set=yes
    - sysctl: name=kernel.core_uses_pid value=1 sysctl_set=yes state=present reload=yes
    - sysctl: name=vm.max_map_count value=1048575 sysctl_set=yes state=present
    - sysctl: name=vm.swappiness value=10 sysctl_set=yes state=present reload=yes   

