---
- hosts: jupiter
  become: true
  tasks:
    - shell: ip link set enp4s0f1 down
    - shell: ip link set enp4s0f1 name eth1
    - shell: ip link set eth1 up
    - lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-enp4s0f1 line="NAME=enp4s0f1" state=absent
    - lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-enp4s0f1 line="DEVICE=enp4s0f1" state=absent
    - lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-enp4s0f1 line="NAME=eth1" state=present
    - lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-enp4s0f1 line="DEVICE=eth1" state=present

    - name: set enp4s0f1
      stat: path=/etc/sysconfig/network-scripts/ifcfg-enp4s0f1
      register: enp4s0f1

    - name: rename to eth1
      command: mv /etc/sysconfig/network-scripts/ifcfg-enp4s0f1 /etc/sysconfig/network-scripts/ifcfg-eth1
      when: enp4s0f1.stat.exists
    - name: restart network
      service: name=network state=restarted

#- hosts: mania:eco:osa
#  become: true
#  tasks:
#    - hostname: name={{ item }}
#      with_items:
#        - poseidon
#        - zeus
#        - jupiter
#        - ceres
#        - hera
#        - dionysos
#        - hermes
#        - demeter
#        - athena
#        - maia
#        - apollo
#        - artemis
#        - ares
#      when: inventory_hostname == item
