---

- hosts: artemis:ares:maia:hermes
  gather_facts: no
  become: yes
  tasks:
      - sysctl: name=fs.file-max value=1000000 sysctl_set=yes
      - sysctl: name=vm.overcommit_memory value=2 sysctl_set=yes
      - sysctl: name=vm.dirty_ratio value=10 sysctl_set=yes
      - sysctl: name=vm.max_map_count value=131072 state=absent
      - sysctl: name=net.ipv4.tcp_synack_retries value=2 sysctl_set=yes
      - sysctl: name=net.ipv4.tcp_rfc1337 value=1 sysctl_set=yes
      - sysctl: name=net.ipv4.tcp_fin_timeout value=15 sysctl_set=yes
      - sysctl: name=net.ipv4.tcp_keepalive_time value=300 sysctl_set=yes
      - sysctl: name=net.ipv4.tcp_keepalive_probes value=5 sysctl_set=yes
      - sysctl: name=net.ipv4.tcp_keepalive_intvl value=15 sysctl_set=yes
      - sysctl: name=net.core.optmem_max value=25165824 sysctl_set=yes
      - sysctl: name=net.ipv4.ip_forward value=1 sysctl_set=yes
      - sysctl: name=net.ipv4.conf.all.forwarding value=1 sysctl_set=yes
      - sysctl: name=net.ipv4.conf.default.forwarding value=1 sysctl_set=yes
      - sysctl: name=net.ipv6.conf.all.forwarding value=1 sysctl_set=yes
      - sysctl: name=net.ipv6.conf.default.forwarding value=1 sysctl_set=yes reload=yes
      - sysctl: name=kernel.sysrq value=0 sysctl_set=yes
      - sysctl: name=fs.suid_dumpable value=0 sysctl_set=yes
      - sysctl: name=kernel.kptr_restrict value=1 sysctl_set=yes
      - sysctl: name=kernel.core_uses_pid value=1 sysctl_set=yes state=present reload=yes

- hosts: artemis:ares:maia:hermes
  gather_facts: no
  become: yes
  tasks:
    - name: noop scheduler for ssd
      command: grubby --update-kernel=ALL --args=elevator=noop
   
    - name: set block device to use noop i/o scheduler sda     
      shell: echo noop > /sys/block/sda/queue/scheduler
    - name: set block device to use noop i/o scheduler sdb
      shell: echo noop > /sys/block/sdb/queue/scheduler
    
    - name: sysctl mmc cass
      sysctl: name=vm.max_map_count value=1048575 sysctl_set=yes state=present
    - name: sysctl swap cass
      sysctl: name=vm.swappiness value=0 sysctl_set=yes state=present reload=yes
   
#- hosts: demeter:apollo
#  become: yes
#  tasks:
#    - name: deadline scheduler for hdd
#      command: grubby --update-kernel=ALL --args=elevator=deadline

#    - name: sda deadline  
#      shell: echo deadline > /sys/block/sda/queue/scheduler
#    - name: sdb deadline   
#      shell: echo deadline > /sys/block/sdb/queue/scheduler
#    - name: sdc deadline   
#      shell: echo deadline > /sys/block/sdc/queue/scheduler
#    - name: sdd deadline  
#      ignore_errors: yes
#      shell: echo deadline > /sys/block/sdd/queue/scheduler


#    - name: sysctl mmc for hera and poseidon
#      sysctl: name=vm.max_map_count value=131072 sysctl_set=yes state=present
#    - name: sysctl swap for hera and poseidon
#      sysctl: name=vm.swappiness value=10 sysctl_set=yes state=present reload=yes


