---
- hosts: jupiter 
  become: yes
  tasks:
    - file: path=/bin/weave state=absent
    - get_url: url=https://git.io/weave dest=/bin/weave mode=777
    - service: name=docker state=restarted
    - name: forward
      shell: iptables -D FORWARD -j REJECT --reject-with icmp-host-prohibited
      ignore_errors: yes
    - name: input
      shell: iptables -D INPUT -j REJECT --reject-with icmp-host-prohibited
      ignore_errors: yes
    - shell: iptables-save
    - name: weave launch
      shell: weave launch 10.0.0.1


#- hosts: hermes
#  become: yes
#  tasks:
#    - shell: weave launch

- hosts: hermes:artemis:ares:athena:maia
  become: yes
  vars:
    weave_env:
        DOCKER_HOST: unix:///var/run/weave/weave.sock
  tasks:
    - name: connect new host
      environment: "{{weave_env}}"
      shell: weave connect 10.0.0.{{ item }}
      with_items:
        - 6

- hosts: jupiter
  become: yes
  vars:
    weave_env:
        DOCKER_HOST: unix:///var/run/weave/weave.sock
  tasks:
    - name: connect to weaveNet
      environment: "{{weave_env}}"
      shell: weave connect 10.0.0.{{ item }}
      with_items:
        - 2
        - 3
        - 4
        - 5
      when: ansible_eth1.ipv4.address != '10.0.0.{{ item }}'
