FROM registry.o-labs.ru/spark:latest                                                                                                                                                                               
COPY start.sh /opt
CMD  [ "/bin/bash", "/opt/start.sh" ]

